# -*- coding: utf-8 -*-
__author__ = 'LiYuanhe'


from Python_Lib.My_Lib_PyQt6 import *
from Python_Lib.My_Lib import *
from .Lib import *
from math import log as ln
from math import sqrt
from math import exp
# from Thermo_Correction_Factors import *

if __name__ == '__main__':
    Application = QApplication(sys.argv)

pyqt_ui_compile(os.path.join(os.path.dirname(__file__), 'UI', 'Batch_Extract_Thermo_Confirm.py'))
from .UI.Batch_Extract_Thermo_Confirm import Ui_Batch_Extract_Thermo_Form

class Thermo_Factor_Form(Ui_Batch_Extract_Thermo_Form,QWidget,Qt_Widget_Common_Functions):
    submit_clicked = pyqtSignal()
    def __init__(self,filename, file_method, file_basis,factor_method,factor_basis, temp=298.15, pressure=1,ZPE_factor=1, H_factor=1, S_factor=1, source=""):
        '''

        :param filename:
        :param file_method: the method used in the output file
        :param file_basis:  the basis used in the output file
        :param factor_method:  the method found in the factor table
        :param factor_basis: the basis found in the factor table
        :param temp:
        :param pressure:
        :param ZPE_factor:
        :param H_factor:
        :param S_factor:
        :param source:
        :return:
        '''
        super(self.__class__, self).__init__()
        self.setupUi(self)

        self.filename = filename
        self.file_method = file_method
        self.file_basis=file_basis
        self.factor_method = factor_method
        self.factor_basis=factor_basis
        self.temp = temp
        self.pressure = pressure
        self.ZPE_factor = ZPE_factor
        self.H_factor = H_factor
        self.S_factor = S_factor
        self.source = source

        self.filename_label.setText(self.filename)
        self.file_method_label.setText(self.file_method)
        self.file_basis_label.setText(self.file_basis)
        self.factor_method_label.setText(self.factor_method)
        self.factor_basis_label.setText(self.factor_basis)
        self.temp_doubleSpinBox.setValue(self.temp-273.15)
        self.pressure_doubleSpinBox.setValue(self.pressure)
        self.ZPE_doubleSpinBox.setValue(self.ZPE_factor)
        self.H_doubleSpinBox.setValue(self.H_factor)
        self.S_doubleSpinBox.setValue(self.S_factor)
        self.source_lineEdit.setText(self.source)

        connect_once(self.submit_pushButton,self.submit_clicked)
        connect_once(self.reset_pushButton,self.reset)

        connect_once(self.temp_doubleSpinBox,self.update_value)
        connect_once(self.pressure_doubleSpinBox,self.update_value)
        connect_once(self.ZPE_doubleSpinBox,self.update_value)
        connect_once(self.H_doubleSpinBox,self.update_value)
        connect_once(self.S_doubleSpinBox,self.update_value)
        connect_once(self.source_lineEdit,self.update_value)
        connect_once(self.same_for_all_checkBox,self.update_value())

        self.show()

    def update_value(self):
        self.temp=self.temp_doubleSpinBox.value()+273.15
        self.pressure=self.pressure_doubleSpinBox.value()*atm__Pa
        self.ZPE_factor=self.ZPE_doubleSpinBox.value()
        self.H_factor=self.H_doubleSpinBox.value()
        self.S_factor=self.S_doubleSpinBox.value()
        self.source=self.source_lineEdit.text()
        self.same_for_all = self.same_for_all_checkBox.isChecked()

    def reset(self):
        self.temp_doubleSpinBox.setValue(298.15)
        self.pressure_doubleSpinBox.setValue(1)
        self.source_lineEdit.setText("")
        self.ZPE_doubleSpinBox.setValue(1)
        self.H_doubleSpinBox.setValue(1)
        self.S_doubleSpinBox.setValue(1)

class Thermo_calculation:
    def __init__(self,input_freq_step:Gaussian_output_step,factor_database = None,
                 manual_specify = False,
                 temp=-1.0,pressure=-1.0,
                 ZPE_factor=1.0, H_factor=1.0, S_factor=1.0, factor_source='Not Scaled'
                 ):
        '''

        :param input_freq_step:
        :param temp: temperature in K
        :param pressure: pressure in Pa
        :param method: QM method for scaling factor
        :param basis:  QM basis for scaling factor
        :param factor_database: a database for scaling factors, generated by gaussianbatchextract,
               should be a list of dict like:{'S(T)': 0.9656, 'Basis': ['pc-0','pc-0'], 'Fundamentals (F)': 'segmented', 'ZPE': 0.9698, 'H(T)-H(0)': 0.9912, 'Fund <1000': 1.021, 'Method': ['B2GP-PLYP','B2GPPLYP'], 'Source': '10.1002/jcc.23073', 'Fund >1000': 0.9464}
               Basis and Method is a two-tuple, each is the method/basis before/after unify

        :return:
        '''

        # all variable, if performed any calculation, is stored as SI unit
        # (variable read directly from Gaussian output doesn't apply)

        self.factor_database = factor_database

        if isinstance(input_freq_step,str):
            print("Implicit step in thermo calculation.")
            assert os.path.isfile(input_freq_step), "File not exist."
            input_freq_step = Gaussian_output(input_freq_step)
            pass

        if isinstance(input_freq_step,Gaussian_output):
            print("Implicit step in thermo calculation.")
            freq_step = [x for x in input_freq_step.steps if x.has_freq and x.normal_termination]
            assert freq_step, "No normal freq step."
            self.freq_step = freq_step[-1]

        if isinstance(input_freq_step,Gaussian_output_step):
            self.freq_step=input_freq_step


        self.molecule = self.freq_step.last_coord
        self.multiplicity = self.molecule.multiplicity
        self.isotopes = self.freq_step.isotopes
        self.mass = sum(self.isotopes)/N_A/1000
        self.is_linear = self.molecule.is_linear()

        self.rotation_symm_number = self.freq_step.rotation_symm_number
        self.moments_of_inertia = self.freq_step.moment_of_inertia # already converted to SI in Lib.py

        self.freqs = self.freq_step.harmonic_freqs
        self.freqs = [x*100*c for x in self.freqs] # cm-1 --> Hz
        self.real_freqs = [x for x in self.freqs if x>0]

        self.method=unify_method(self.freq_step.method)
        self.basis=unify_basis(self.freq_step.basis)

        self.temp=temp
        self.pressure=pressure
        self.ZPE_factor=ZPE_factor
        self.H_factor=H_factor
        self.S_factor=S_factor
        self.factor_source=factor_source
        self.same_for_all=True

        if not manual_specify and self.method and self.basis:
            for line in self.factor_database:
                if self.method==line['Method'][1] and self.basis==line['Basis'][1]:
                    scaling_line=line
                    print(line)
                    print("Please Verify:")
                    print("Automatic search result of scaling factor for METHOD:",scaling_line['Method'][0]," BASIS:",scaling_line['Basis'][0])
                    ZPE_factor = scaling_line['ZPE']
                    S_factor = scaling_line['S(T)']
                    H_factor = scaling_line['H(T)-H(0)']
                    factor_source = scaling_line['Source']
                    print("Scaling factors: ZPE:",ZPE_factor,' H(0->T):',H_factor," S(T):",S_factor,' Source:',factor_source)


                    thermo_factor_dialog = Thermo_Factor_Form(self.freq_step.filename,
                                                              self.freq_step.method,
                                                              self.freq_step.basis,
                                                              scaling_line['Method'][0],
                                                              scaling_line['Basis'][0],
                                                              self.freq_step.temp,
                                                              self.freq_step.pressure,
                                                              ZPE_factor,
                                                              H_factor,
                                                              S_factor,
                                                              factor_source)

                    thermo_factor_dialog.exec_()
                    self.temp = thermo_factor_dialog.temp
                    self.pressure = thermo_factor_dialog.pressure
                    self.ZPE_factor=thermo_factor_dialog.ZPE_factor
                    self.H_factor=thermo_factor_dialog.H_factor
                    self.S_factor=thermo_factor_dialog.S_factor
                    self.factor_source=thermo_factor_dialog.source
                    self.same_for_all = thermo_factor_dialog.same_for_all

                    break

        if self.temp==-1:
            self.temp = self.freq_step.temp

        if self.pressure==-1:
            self.pressure = self.freq_step.pressure*atm__Pa

        self.scaling()

    def translate(self):

        T = self.temp
        P = self.pressure
        m = self.mass

        q = ((2*pi*m*k_B*T/h**2)**(3/2))*R*T/P

        trans = {}
        trans['q'] = q
        trans['q/N'] = q/N_A

        trans['C_V'] = 3/2 * R
        trans['C_P'] = 5/2 * R

        trans['U(T)'] = 3/2 * R * T
        trans['H(T)'] = 5/2 * R * T

        trans['S(T)'] = R * ( ln(q/N_A) + 5/2 )

        self.translation_dict = trans

        # print(trans)

    def rotation(self):
        T = self.temp
        I_A, I_B, I_C = self.moments_of_inertia
        sigma = self.rotation_symm_number
        # print(I_A,I_B,I_C,sigma)

        rotation = {}

        if self.is_linear:
            q = 8*pi**2*I_A*k_B*T / sigma / h**2

            rotation['q'] = q
            rotation['U(T)'] = R*T
            rotation['C_V'] = R
            rotation['S(T)'] = R*( ln(q) + 1 )

        else:
            q = (8*pi**2 / sigma / h**3)*(2*pi*k_B*T)**(3/2)*sqrt(I_A*I_B*I_C)
            rotation['q'] = q
            rotation['U(T)'] = 3/2*R*T
            rotation['C_V'] = 3/2*R
            rotation['S(T)'] = R*( ln(q) + 3/2 )

        self.rotation_dict = rotation








        # print(rotation)

    def vibration(self):
        T = self.temp

        vibration = {key:[] for key in ['q(BOT)', 'q(V=0)',
                                        'U(0)','ZPE', 'U(0->T)', "U(T)",
                                        'C_V',
                                        'S(T)']}

        for nu in self.real_freqs:

            reduced_freq = h*nu/k_B/T
            freq_exp = exp(-reduced_freq)
        
            vibration['q(BOT)'  ].append(sqrt(freq_exp)/(1-freq_exp))
            vibration['q(V=0)'  ].append(1/(1-freq_exp))
            vibration['U(0)'    ].append(1/2*h*nu*N_A)
            vibration['U(0->T)' ].append(R*T*(reduced_freq)*(freq_exp/(1-freq_exp)))
            vibration['U(T)'    ].append(vibration['U(0->T)'][-1]+vibration['U(0)'][-1])
            vibration['C_V'     ].append(R*(reduced_freq)**2 * (freq_exp/(1-freq_exp)**2))
            vibration['S(T)'    ].append(R*( (reduced_freq) * (freq_exp/(1-freq_exp)) - ln(1-freq_exp)))

        vibration['ZPE'] = vibration['U(0)']

        self.vibration_dict = vibration

        # for items in self.vibration_dict.items():
        #     print(items)

    def electronic(self):
        self.electronic_dict = {"q"     :self.multiplicity,
                                'S(T)'  :R*ln(self.multiplicity)}

    def total(self):

        from numpy import prod
        self.translate()
        self.rotation()
        self.vibration()
        self.electronic()

        T = self.temp

        trans = self.translation_dict
        rot = self.rotation_dict
        vib = self.vibration_dict
        elec = self.electronic_dict

        total = {}
        total['q(BOT)'  ] = trans['q/N'] * rot['q'] * prod(vib['q(BOT)']) * elec['q']
        total['q(V=0)'  ] = trans['q/N'] * rot['q'] * prod(vib['q(V=0)']) * elec['q']
        total['C_V'     ] = trans['C_V']+rot['C_V']+sum(vib['C_V'])
        total['C_P'     ] = total['C_V'] + R
        total['S(T)'    ] = trans['S(T)']+rot['S(T)']+sum(vib['S(T)'])+elec['S(T)']

        total["ZPE" ] = sum(vib['ZPE'])
        total['U(T)'] = trans['U(T)']+rot['U(T)']+sum(vib['U(T)'])
        total['H(T)'] = total['U(T)'] + R*T
        total['G(T)'] = total['H(T)'] - T*total['S(T)']
        total['H(0->T)'] = total["H(T)"]-total['ZPE']

        self.total_dict=total



    # def print_total(self):
    #     for item in self.total_dict.items():
    #         print(item)

    def __str__(self):
        ret = []
        for item in self.total_dict.items():
            ret.append(repr(item))
        ret.sort()
        return "\n".join(ret)

    def scaling(self):
        self.total()
        T = self.temp
        total = self.total_dict
        total['ZPE Factor'] = self.ZPE_factor
        total['S Factor'] = self.S_factor
        total['H Factor'] = self.H_factor
        total['Temp'] = self.temp
        total['Pressure'] = self.pressure
        total['Factor Source'] = self.factor_source

        total['ZPE_Corr'] =total['ZPE']*self.ZPE_factor
        total['H(0->T)_Corr'] = total['H(0->T)']*self.H_factor
        total['S(T)_Corr'] = total['S(T)']*self.S_factor
        total['G(T)_Corr'] = total['ZPE_Corr'] + total['H(0->T)_Corr'] - T*total['S(T)_Corr']

        self.total_dict = total

        # print(self)

if __name__ == '__main__':
    sample_file = r"E:\常用程序\0化学\Shermo\34epi_GroupLeaders_sdf_G01__M001__0_00_34epi_P8_8[Opt_B3LYP_DZ].out"
    a=Thermo_calculation(sample_file,factor_database=load_factor_database(),temp=373.15)
    a.scaling()
    # a.scaling(manual_specify=True,ZPE_factor=0.9813,H_factor=1.0004,S_factor=1.0029)
    print(a)
